In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [5]:
# graph_object
# express
import plotly.graph_objects as go
import plotly.express as px

In [ ]:
# using graph objects
# add_trace>>adding data
# scatter plot
fig=go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,4,5],y=[1,7,8,2,6],mode="markers"))

In [10]:
# line chart
fig=go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,4,5],y=[1,7,8,2,6],mode="lines"))

In [11]:
tips=sns.load_dataset("tips")

In [12]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [14]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill,y=tips.tip,mode="markers"))

In [16]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill,y=tips.tip,mode="lines"))

In [17]:
fig=go.Figure()
fig.add_trace(go.Bar(x=[1,2,3,4,5,6],y=[3,8,9,5,7,2]))

In [18]:
fig=go.Figure()
fig.add_trace(go.Histogram(x=tips["total_bill"]))

In [19]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill,y=tips.tip,mode="markers"))

In [20]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=tips.total_bill,y=tips.tip,mode="markers",marker_size=12*tips["size"]))

In [24]:
fig=go.Figure()
fig.add_trace(go.Scatter3d(x=tips.total_bill,y=tips.tip,mode="markers",marker_size=12*tips["size"],z=tips["size"]))

In [25]:
fig=go.Figure()
fig.add_trace(go.Scatter3d(x=[1,2,3,4,5],y=[3,8,5,2,6],z=[1,2,7,3,5]))

In [26]:
# using plotly express px
x=[1,2,3,4]
y=[10,13,14,15]
fig=px.scatter(x,y)
fig.show()

In [27]:
fig=px.line(x,y)
fig.show()

In [28]:
x=["A","B","C"]
y=[10,5,6]
fig=px.bar(x=x,y=y)
fig.show()

In [29]:
x=[5,10,3,5,5,6,6,10,10,3,11,11,12,3,4,]
fig=px.histogram(x)
fig.show()

In [30]:
x=["A","B","C"]
y=[5,10,3,25,12,33,100]
fig=px.box(x,y)
fig.show()

In [31]:
data=[[1,2,3],[4,5,6],[7,8,9]]
fig=px.imshow(data)
fig.show()

In [33]:
# Bubble chart
x=[1,2,3,4]
y=[5,8,12,3]
px.scatter(x,y,size=[30,10,50,100])
fig.show()

In [34]:
# 3d chart
x=[1,2,3,4]
y=[5,8,12,3]
z=[3,4,5,6]
fig=px.scatter_3d(x=x,y=y,z=z)
fig.show()

In [35]:
# contour plot
x=[1,2,3,4,3,23,80]
y=[5,8,12,3,12,35,60]
px.density_contour(x,y)