In [ ]:
#Pandas is a fast ,powerful.flexible and easy to use open source data analysis and manipulation.
#Built on top of the python programming language.

# 2008 by Mckinney
# very useful with structured data(tabular data )

In [2]:
import pandas as pd

In [ ]:
import pandas as pd
df=pd.read_csv("student_records (1).csv")
 # Read a comma-seprated values (csv) file into DataFrame.

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
# By default pandas understand the first rows as the column name
pd.read_csv("student_records (1).csv",header=None) #internal integer indexes are provided by pandas for both rows and column.

        0             1         2              3             4          5
0    Name  OverallGrade  Obedient  ResearchScore  ProjectScore  Recommend
1   Henry             A         Y             90            85        Yes
2    John             C         N             85            51        Yes
3   David             F         N             10            17         No
4  Holmes             B         Y             75            71         No
5  Marvin             E         N             20            30         No
6   Simon             A         Y             92            79        Yes
7  Robert             B         Y             60            59         No
8   Trent             C         Y             75            33         No

In [17]:
pd.read_csv("student_records (1).csv",skiprows=2)

     John  C  N  85  51  Yes
0   David  F  N  10  17   No
1  Holmes  B  Y  75  71   No
2  Marvin  E  N  20  30   No
3   Simon  A  Y  92  79  Yes
4  Robert  B  Y  60  59   No
5   Trent  C  Y  75  33   No

In [18]:
pd.read_csv("student_records (1).csv",usecols=['ResearchScore','ProjectScore'])

   ResearchScore  ProjectScore
0             90            85
1             85            51
2             10            17
3             75            71
4             20            30
5             92            79
6             60            59
7             75            33

In [19]:
df=pd.read_csv("student_records (1).csv")

In [20]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [ ]:
# data structure>> series and dataframe
# series>> 1 dimensional in nature
# dataframe>> 2 dimensional in nature,multiple series combines to form a dataframes(rows and columns)

In [21]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
type([1,2,3])

list

In [24]:
df.OverallGrade

0    A
1    C
2    F
3    B
4    E
5    A
6    B
7    C
Name: OverallGrade, dtype: object

In [25]:
df["OverallGrade"]

0    A
1    C
2    F
3    B
4    E
5    A
6    B
7    C
Name: OverallGrade, dtype: object

In [ ]:
type(df["OverallGrade"]) # a column is a series of dataframe

pandas.core.series.Series

In [27]:
l=[1,2,3,4,5,6]
s=pd.Series(l)

In [28]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [29]:
s[1:]

1    2
2    3
3    4
4    5
5    6
dtype: int64

In [30]:
s[2:4]

2    3
3    4
dtype: int64

In [33]:
# By default indexes are integer,we can have customer indexes
d=pd.Series([100,200,300],index=["Ajay","Bijay",1])

In [34]:
d

Ajay     100
Bijay    200
1        300
dtype: int64

In [35]:
type(d)

pandas.core.series.Series

In [36]:
d["Ajay"]

np.int64(100)

In [37]:
# to see all the index of a series
d.index

Index(['Ajay', 'Bijay', 1], dtype='object')

In [38]:
# to reset index
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [39]:
pd.DataFrame(d)

         0
Ajay   100
Bijay  200
1      300

In [40]:
df.head(5)

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No

In [41]:
df.head(2)

    Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Henry            A        Y             90            85       Yes
1   John            C        N             85            51       Yes

In [42]:
df.tail(2)

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

In [43]:
df.shape

(8, 6)

In [44]:
df.columns

Index(['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore',
       'Recommend'],
      dtype='object')

In [45]:
list(df.columns)

['Name',
 'OverallGrade',
 'Obedient',
 'ResearchScore',
 'ProjectScore',
 'Recommend']

In [46]:
df.head()

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No

In [48]:
df.sample(3)

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
7   Trent            C        Y             75            33        No
1    John            C        N             85            51       Yes
4  Marvin            E        N             20            30        No

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8 non-null      object
 1   OverallGrade   8 non-null      object
 2   Obedient       8 non-null      object
 3   ResearchScore  8 non-null      int64
 4   ProjectScore   8 non-null      int64
 5   Recommend      8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

In [50]:
df.dtypes

Name             object
OverallGrade     object
Obedient         object
ResearchScore     int64
ProjectScore      int64
Recommend        object
dtype: object

In [51]:
df["ProjectScore"]

0    85
1    51
2    17
3    71
4    30
5    79
6    59
7    33
Name: ProjectScore, dtype: int64

In [52]:
list(df["ProjectScore"])

[85, 51, 17, 71, 30, 79, 59, 33]

In [53]:
# Series to a dataframe
s=pd.Series([2,3,4],index=[100,"Ajay",200])
s

100     2
Ajay    3
200     4
dtype: int64

In [54]:
d=pd.DataFrame(s)

In [55]:
d

      0
100   2
Ajay  3
200   4

In [56]:
type(d)

pandas.core.frame.DataFrame

In [57]:
d["new column"]="Nikhil"

In [58]:
d

      0 new column
100   2     Nikhil
Ajay  3     Nikhil
200   4     Nikhil

In [ ]:
d["new column"] # best way to access the column this way but if its a continuous string,you can access using df.column_name

100     Nikhil
Ajay    Nikhil
200     Nikhil
Name: new column, dtype: object

In [61]:
d

      0 new column
100   2     Nikhil
Ajay  3     Nikhil
200   4     Nikhil

In [ ]:
d['new_column2']=[1,2,3] # no of new column elements should be equal to no of rows

In [64]:
d

      0 new column  new_column2
100   2     Nikhil            1
Ajay  3     Nikhil            2
200   4     Nikhil            3

In [65]:
# change columns name 
d.columns=["col1","col2","col3"]

In [66]:
d

      col1    col2  col3
100      2  Nikhil     1
Ajay     3  Nikhil     2
200      4  Nikhil     3

In [68]:
# reset_index
d.reset_index(drop=True)

   col1    col2  col3
0     2  Nikhil     1
1     3  Nikhil     2
2     4  Nikhil     3

In [69]:
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No